#==================================================
#   Description: dein.toml
#   Author: n-shinoda
#   Last Modified: 2019-02-01
#==================================================

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'

[[plugins]] # Denite.nvim is a dark powered Neovim unite all interfaces. 
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/.vim/config/plugins-config/denite_config.vim
'''

[[plugins]] # ステータスラインの表示内容が強化するプラグイン
repo = 'itchyny/lightline.vim'
hook_add = '''
    source ~/.vim/config/plugins-config/lightline_config.vim
'''

[[plugins]] # インデントを見やすくする
repo = 'Yggdroot/indentLine'

[[plugins]] # 閉じ括弧を補完する
repo = 'cohama/lexima.vim'

[[plugins]] # ES6のシンタックスハイライト
repo = 'othree/yajs.vim'
hook_add = '''
    source ~/.vim/config/plugins-config/yajs_config.vim
'''

# [[plugins]] # Git操作用プラグイン
# repo = 'tpope/vim-fugitive'

[[plugins]] # ディレクトリをツリー表示する
repo = 'scrooloose/nerdtree'
hook_add = '''
    source ~/.vim/config/plugins-config/NERDTree_config.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup   = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i = 1;
hook_source = '''
" Plugin key-mappings.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

" SuperTab like snippets behavior.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
"imap <expr><TAB>
" \ pumvisible() ? "\<C-n>" :
" \ neosnippet#expandable_or_jumpable() ?
" \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

" smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
" \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

 For conceal markers.
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif 
'''

[[plugins]] # colorscheme
repo = 'cocopon/iceberg.vim'

# [[plugins]] # colorscheme
# repo = 'jonathanfilip/vim-lucius'

# [[plugins]] # colorscheme
# repo = 'johngrib/vim-dracula'

# [[plugins]] # colorscheme
# repo = 'tomasr/molokai'

# [[plugins]] # colorscheme
# repo ='herrbischoff/cobalt2.vim'

