#===============================================================
#   Description: dein_lazy.toml
#   Author: N-Shinoda
#   Last Modified: 2019-08-28
#===============================================================

#===============================================================
# Shougo/deoplete.nvim
# 自動補完システム(dark powered neo-completion)
#===============================================================
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
on_event = 'InsertEnter'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 0
    let g:deoplete#auto_complete_start_length = 1
    let g:deoplete#enable_camel_case = 0
    let g:deoplete#enable_ignore_case = 0
    let g:deoplete#enable_refresh_always = 0
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#file#enable_buffer_path = 1
    let g:deoplete#max_list = 10000
    set completeopt-=preview
    inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
    inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
'''

#===============================================================
# zchee/deoplete-clang
# deopleteの補完ソース
#===============================================================
[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
depends = ['deoplete.nvim']

#===============================================================
# Shougo/neoinclude.vim
# ヘッダファイルの補完
#===============================================================
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

#===============================================================
# Shougo/neosnippet.vim
# スニペット機能を追加
#===============================================================
[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
hook_source = '''
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
    if has('conceal')
      set conceallevel=2 concealcursor=niv
    endif
    let g:neosnippet#enable_snipmate_compatibility = 1
    let g:neosnippet#enable_completed_snippet = 1
    let g:neosnippet#expand_word_boundary = 1
    let g:neosnippet#enable_completed_snippet = 1
'''
hook_add = '''
    let g:neosnippet#snippets_directory = "$XDG_CONFIG_HOME/nvim/autoload/snippets/"
'''
#===============================================================
# Shougo/neosnippet-snippets
# スニッペットを集めた定義ファイル群
#===============================================================
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

#===============================================================
# rhysd/vim-clang-format
# C/C++の入力補完をしてくれるプラグイン
#===============================================================
[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = 'cpp'

