#===============================================================
#   Description: dein_lazy.toml
#   Author: N-Shinoda
#   Last Modified: 2022-01-27
#===============================================================

#===============================================================
# Shougo/deoplete.nvim
# 自動補完システム(dark powered neo-completion)
#===============================================================
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
on_event = 'InsertEnter'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
    inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
'''

#===============================================================
# zchee/deoplete-clang
# deopleteの補完ソース
#===============================================================
[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
hook_source = '''
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-10/lib/libclang-10.so.1'
    let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''
depends = ['deoplete.nvim']

#===============================================================
# Shougo/neoinclude.vim
# ヘッダファイルの補完
#===============================================================
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

