#===============================================================
#   Description: dein.toml
#   Author: N-Shinoda
#   Last Modified: 2021-02-09
#===============================================================

#===============================================================
# colorscheme
# カラースキーム
#===============================================================
[[plugins]]
repo = 'cocopon/iceberg.vim'

# [[plugins]]
# repo = 'jonathanfilip/vim-lucius'

# [[plugins]]
# repo = 'johngrib/vim-dracula'

#===============================================================
# Shougo/dein.vim
# プラグインマネージャ
#===============================================================
[[plugins]]
repo = 'Shougo/dein.vim'

#===============================================================
# Shougo/denite.nvim
# 一覧から特定のデータを検索してアクションを実行する
#===============================================================
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    nnoremap <Space> [denite]
    nnoremap <Space>p [deniteProject]
    nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
    nnoremap <silent> [denite]g :<C-u>Denite grep<CR>
    nnoremap <silent> [denite]m :<C-u>Denite file_mru<CR> <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
    nnoremap <silent> [denite]f :<C-u>Denite file/rec<CR>
    nnoremap <silent> [denite]d :<C-u>Denite directory_rec<CR>
    nnoremap <silent> [deniteProject]b :<C-u>DeniteProject buffer<CR>
    nnoremap <silent> [deniteProject]g :<C-u>DeniteProject grep<CR>
    nnoremap <silent> [deniteProject]m :<C-u>DeniteProject file_mru<CR> <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
    nnoremap <silent> [deniteProject]f :<C-u>DeniteProject file/rec<CR>
    nnoremap <silent> [deniteProject]d :<C-u>DeniteProject directory_rec<CR>
'''
hook_source = '''
    if executable('rg')
        call denite#custom#var('file/rec', 'command', ['rg', '--files', '--glob', '!.git'])
        call denite#custom#var('file_rec', 'command', ['rg', '--files', '--glob', '!.git'])
        call denite#custom#var('grep', 'command', ['rg', '--threads', '1'])
        call denite#custom#var('grep', 'recursive_opts', [])
        call denite#custom#var('grep', 'final_opts', [])
        call denite#custom#var('grep', 'separator', ['--'])
call        call denite#custom#var('grep', 'default_opts', ['--vimgrep', '--no-heading'])
    endif
    call denite#custom#map('insert', "<C-n>", '<denite:move_to_next_line>')
    call denite#custom#map('insert', "<C-p>", '<denite:move_to_previous_line>')
    call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
    call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
    call denite#custom#map('insert', "<C-h>", '<denite:do_action:split>')
    call denite#custom#filter('matcher_ignore_globs', 'ignore_globs', [
                \ '.git/', 'build/', '__pycache__/',
                \ 'images/', '*.o', '*.make', '*.min.*',
                \ 'img/', 'fonts/', '*~', '*.exe', '*.bak',
                \ '.DS_Store', '*.pyc', '*.class', 'tags'
                \ ])
'''
#===============================================================
# Yggdroot/indentLine
# インデントを見やすくする
#===============================================================
[[plugins]]
repo = 'Yggdroot/indentLine'

#===============================================================
# cohama/lexima.vim
# 閉じ括弧を補完する
#===============================================================
[[plugins]]
repo = 'cohama/lexima.vim'

#===============================================================
# vim-airline/vim-airline
# ステータスラインの表示内容が強化するプラグイン
#===============================================================
[[plugins]]  
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']
hook_add = '''
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    nnoremap <C-p> <Plug>AirlineSelectPrevTab
    nnoremap <C-n> <Plug>AirlineSelectNextTab
'''

#===============================================================
# vim-airline/vim-airline-themes
# vim-airlineのテーマ
#===============================================================
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  set laststatus=2
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#whitespace#mixed_indent_algo = 1
  let g:airline_theme = 'papercolor'
'''

#===============================================================
# scrooloose/nerdtree
# ディレクトリをツリー表示する
#===============================================================
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    " 隠しファイルを設定する
    let NERDTreeShowHidden = 1
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

#===============================================================
# alvan/vim-closetag
# HTMLやXMLのタグを自動で閉じる
#===============================================================
[[plugins]]  
repo = 'alvan/vim-closetag'  
hook_add = '''  
  let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.erb,*.php,*.vue'  
'''  

#===============================================================
# tpope/vim-fugitive
# vim上でgitを操作する
#===============================================================
[[plugins]]
repo = 'tpope/vim-fugitive'

#===============================================================
# rust-lang/rust.vim
#===============================================================
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
    let g:rustfmt_autosave = 1
'''
